version: "3.8"

services:
  flateos:
    image: "archlinux:latest"
    container_name: "flateos"
    restart: unless-stopped
    working_dir: "/src"
    entrypoint: "./bootstrap.sh"
    networks:
      - flateos-net
    privileged: true
    tty: true
    volumes:
      - .:/src
      - $DIR__KEYS:/keys
    env_file: .env

networks:
  flateos-net:
    driver: bridge
